server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "app-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "app"
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            span_id: span_id


