services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra_cluster
    volumes:
      - ./init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/init-schema.sh"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # web:
  #   build: .
  #   depends_on:
  #     - cassandra
  #   container_name: webapp
  #   networks:
  #     - cassandra-net
  #   environment:
  #     - CASSANDRA_HOST=cassandra 
  #     - NODE_NAME=webapp
  #     - CASSANDRA_KEYSPACE="tagging"

networks:
  cassandra-net:
    driver: bridge