version: '3.8'

networks:
  cassandra:

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra3"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      MAX_HEAP_SIZE: '1G'
      HEAP_NEWSIZE: '500M'
    volumes:
      - ./cassandra-dc1-node1/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./cassandra-dc1-node1/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra-dc1-node1/lib:/var/lib/cassandra
      - ./cassandra-dc1-node1/logs:/var/log/cassandra
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '4G'
        reservations:
          cpus: '2'
          memory: '2G'

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra
    ports:
      - "9043:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra3"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      MAX_HEAP_SIZE: '1G'
      HEAP_NEWSIZE: '500M'
    depends_on:
      cassandra1:
        condition: service_started
    volumes:
      - ./cassandra-dc1-node2/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./cassandra-dc1-node2/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - /cassandra-dc1-node2/lib:/var/lib/cassandra
      - /cassandra-dc1-node2/logs:/var/log/cassandra
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '4G'
        reservations:
          cpus: '2'
          memory: '2G'

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra
    ports:
      - "9044:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra3"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      MAX_HEAP_SIZE: '1G'
      HEAP_NEWSIZE: '500M'
    volumes:
      - ./cassandra-dc2-node1/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./cassandra-dc2-node1/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra-dc2-node1/lib:/var/lib/cassandra
      - ./cassandra-dc2-node1/logs:/var/log/cassandra
    depends_on:
      cassandra1:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '4G'
        reservations:
          cpus: '2'
          memory: '2G'

  cassandra4:
    image: cassandra:latest
    container_name: cassandra4
    hostname: cassandra4
    networks:
      - cassandra
    ports:
      - "9045:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra3"
      CASSANDRA_CLUSTER_NAME: MyTestCluster
      MAX_HEAP_SIZE: '1G'
      HEAP_NEWSIZE: '500M'
    volumes:
      - ./cassandra-dc2-node2/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./cassandra-dc2-node2/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./cassandra-dc2-node2/lib:/var/lib/cassandra
      - ./cassandra-dc2-node2/logs:/var/log/cassandra
    depends_on:
      cassandra3:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '4G'
        reservations:
          cpus: '2'
          memory: '2G'